### ISSUE TITLE
Implement Favicon 

### ISSUE THREAD

**Issue by Its-Aman-Yadav** [Its-Aman-Yadav/My-Portfolio#2]
Hey, add a cool favicon of a minimalist boy character

**Comment by AKSH2002** [comment]
Hi Aman, I have submitted a pull request for the issue. Could you please review it and provide your feedback? I would appreciate any changes or suggestions you may have. Thank you!

**Comment by Its-Aman-Yadav** [comment]
It looks good, thanks
